Add optional full_history boolean flag
philips-software/inner-source-checkout-action pull request #173
Opened 2022-05-08 21:08 UTC by JeroenKnoops

Add optional `full_history` argument.

When set to `true` the repository is being checked out with the complete history.
If set to `false` (the default), the repository is being checked out with `depth=1`

Default value is `false`.

cc @vanGastelJS

2022-05-16 07:52 UTC, vanGastelJS commented
@npalm: Could you please review this pull request as I need this for correct builds using build automation. Github does not (yet) support git submodules.

2022-05-16 08:10 UTC, npalm requested changes
@vanGastelJS just one small suggestion. Thanks for the contribution.

2022-05-16 08:10 UTC, npalm commented on action.yml
> +    description: Full Checkout of the repository
```suggestion
    description: By defaullt a shallow clone with depth 1 is created. Set to `true` to clone the repo will a full history.
```

2022-05-18 08:52 UTC, vanGastelJS commented
@npalm: Could you please review the updated pull request? And if ok, could you also release this feature so I can use it in our automated builds?

2022-05-18 09:49 UTC, npalm approved these changes

2022-05-18 09:49 UTC, merged